[package]
name = "reth-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-network.workspace = true
reth-net-nat.workspace = true
reth-discv4.workspace = true
reth-primitives.workspace = true

# serde
serde.workspace = true
humantime-serde.workspace = true

# crypto
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }

[dev-dependencies]
confy.workspace = true
tempfile.workspace = true
toml.workspace = true
