version: "3.9"
name: "reth"

services:
    base-geth:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:latest
        volumes:
            - ~/base:/base
            - ./jwttoken:/root/jwt:ro
        ports:
            - "6545:6545"
            - "6546:6546"
            - "30305:30305/tcp"
            - "30305:30305/udp"
        command: >
            --datadir=/base
            --http
            --http.corsdomain="*"
            --http.vhosts="*"
            --http.addr=0.0.0.0
            --http.port=6545
            --http.api=web3,debug,eth,txpool,net,engine
            --ws
            --ws.addr=0.0.0.0
            --ws.port=6546
            --ws.origins="*"
            --ws.api=debug,eth,txpool,net,engine
            --authrpc.addr="0.0.0.0"
            --authrpc.port="6551"
            --authrpc.vhosts="*"
            --authrpc.jwtsecret=/root/jwt/jwt.hex
            --syncmode=snap
            --gcmode=full
            --maxpeers=100
            --rollup.disabletxpoolgossip=true
            --rollup.sequencerhttp=https://mainnet-sequencer.base.org
            --op-network=base-mainnet
            --discovery.port=30305
            --port=30305
            --bootnodes=enode://87a32fd13bd596b2ffca97020e31aef4ddcc1bbd4b95bb633d16c1329f654f34049ed240a36b449fda5e5225d70fe40bc667f53c304b71f8e68fc9d448690b51@3.231.138.188:30301,enode://ca21ea8f176adb2e229ce2d700830c844af0ea941a1d8152a9513b966fe525e809c3a6c73a2c18a12b74ed6ec4380edf91662778fe0b79f6a591236e49e176f9@184.72.129.189:30301,enode://acf4507a211ba7c1e52cdf4eef62cdc3c32e7c9c47998954f7ba024026f9a6b2150cd3f0b734d9c78e507ab70d59ba61dfe5c45e1078c7ad0775fb251d7735a2@3.220.145.177:30301,enode://8a5a5006159bf079d06a04e5eceab2a1ce6e0f721875b2a9c96905336219dbe14203d38f70f3754686a6324f786c2f9852d8c0dd3adac2d080f4db35efc678c5@3.231.11.52:30301,enode://cdadbe835308ad3557f9a1de8db411da1a260a98f8421d62da90e71da66e55e98aaa8e90aa7ce01b408a54e4bd2253d701218081ded3dbe5efbbc7b41d7cef79@54.198.153.150:30301
        stop_grace_period: 5m
    base-op-node:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:latest
        restart: unless-stopped
        volumes:
            - ./rollup:/root/rollup:ro
            - ./jwttoken:/root/jwt:ro
        ports:
            - "6000:6000" # rpc
            - "6003:6003"
        command: >
            op-node
              --l1=ws://reth:8546
              --l1.trustrpc
              --l2=ws://base-geth:6551
              --l2.jwt-secret=/root/jwt/jwt.hex
              --rpc.addr=0.0.0.0
              --rpc.port=6000
              --network=base-mainnet
              --rollup.config=/root/rollup/base/rollup.json
              --l1.beacon=http://lighthouse:5052
              --syncmode=execution-layer
        depends_on:
            - reth
            - base-geth
            - lighthouse

volumes:
    base:
        driver: local
