version: "3.9"
name: "reth"

services:
    base-geth:
        stop_grace_period: 5m
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
        volumes:
            - ~/base:/base
            - ./jwttoken:/root/jwt:ro
        ports:
            - "6545:6545"
            - "6546:6546"
            - "30305:30305/tcp"
            - "30305:30305/udp"
        command: >
            --datadir=/base
            --http
            --http.corsdomain="*"
            --http.vhosts="*"
            --http.addr=0.0.0.0
            --http.port=6545
            --http.api=web3,debug,eth,txpool,net,engine
            --ws
            --ws.addr=0.0.0.0
            --ws.port=6546
            --ws.origins="*"
            --ws.api=debug,eth,txpool,net,engine
            --authrpc.addr="0.0.0.0"
            --authrpc.port="6551"
            --authrpc.vhosts="*"
            --authrpc.jwtsecret=/root/jwt/jwt.hex
            --syncmode=snap
            --gcmode=full
            --maxpeers=100
            --rollup.disabletxpoolgossip=true
            --rollup.sequencerhttp=https://mainnet-sequencer.base.org
            --rollup.halt=major
            --op-network=base-mainnet
            --discovery.port=30305
            --port=30305
    base-op-node:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
        restart: unless-stopped
        volumes:
            - ./rollup:/root/rollup:ro
            - ./jwttoken:/root/jwt:ro
        ports:
            - "6000:6000" # rpc
            - "6003:6003"
        command: >
            op-node
              --l1=ws://reth:8546
              --l1.trustrpc
              --l2=ws://base-geth:6551
              --l2.jwt-secret=/root/jwt/jwt.hex
              --rollup.config=/root/rollup/base/rollup.json
              --rpc.addr=0.0.0.0
              --rpc.port=6000
              --network=base-mainnet
              --l1.beacon=http://lighthouse:5052
              --syncmode=execution-layer
        depends_on:
            - reth
            - base-geth
            - lighthouse

volumes:
    base:
        driver: local
