version: "3.9"
name: "op-reth"

services:
    op-reth:
        restart: unless-stopped
        image: rickybarnett/op-reth
        ports:
            - "9001:9001" # metrics
            - "30304:30304" # eth/66 peering
            - "7545:7545" # rpc
            - "7546:7546" # ws
            - "9551:9551" # engine
        volumes:
            - ~/rethdata_base:/root/.local/share/reth/base/db
            - ~/rethlogs:/root/rethlogs
            - ./jwttoken:/root/jwt:ro
        # For Sepolia, replace `--chain mainnet` with `--chain sepolia`
        command: >
            node
            --chain base
            --rollup.sequencer-http https://sequencer.base.org
            --authrpc.addr 0.0.0.0
            --authrpc.port 9551
            --authrpc.jwtsecret /root/jwt/jwt.hex
            --http --http.addr 0.0.0.0 --http.port 7545
            --http.corsdomain "*"
            --http.api "eth,net,web3,txpool,admin,eth-call-bundle,debug,trace"
            --ws --ws.addr 0.0.0.0 --ws.port 7546
            --ws.origins "*"
            --ws.api "eth,net,web3,txpool,admin,eth-call-bundle,debug,trace"
            --rpc-max-response-size 9999999

volumes:
    rethdata_base:
        driver: local
