version: "3.9"
name: "reth"

services:
    reth:
        restart: unless-stopped
        image: ghcr.io/paradigmxyz/reth
        ports:
            - "9001:9001" # metrics
            - "30303:30303" # eth/66 peering
            - "8545:8545" # rpc
            - "8546:8546" # ws
            - "8551:8551" # engine
        volumes:
            - ~/rethdata_mainnet:/root/.local/share/reth/mainnet/db
            - ~/rethdata_sepolia:/root/.local/share/reth/sepolia/db
            - ~/rethdata_goerli:/root/.local/share/reth/goerli/db
            - ~/rethlogs:/root/rethlogs
            - ./jwttoken:/root/jwt:ro
        # For Sepolia, replace `--chain mainnet` with `--chain sepolia`
        command: >
            node
            --chain mainnet
            --metrics 0.0.0.0:9001
            --log.file.directory /root/rethlogs
            --authrpc.addr 0.0.0.0
            --authrpc.port 8551
            --authrpc.jwtsecret /root/jwt/jwt.hex
            --http --http.addr 0.0.0.0 --http.port 8545
            --http.corsdomain "*"
            --http.api "eth,net,web3,txpool,admin,eth-call-bundle,debug,trace"
            --ws --ws.addr 0.0.0.0 --ws.port 8546
            --ws.origins "*"
            --ws.api "eth,net,web3,txpool,admin,eth-call-bundle,debug,trace"
            --rpc-max-response-size 9999999

    simulator:
        restart: unless-stopped
        image: rickybarnett/simulator
        depends_on:
            - reth
        ports:
            - 8001:8080

volumes:
    rethdata_mainnet:
        driver: local
    rethdata_sepolia:
        driver: local
    rethdata_goerli:
        driver: local
    rethlogs:
        driver: local
    prometheusdata:
        driver: local
    grafanadata:
        driver: local
