version: "3.9"
name: "reth"

services:
    base-geth:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
        volumes:
            - ~/base:/base
            - ./jwttoken:/root/jwt:ro
        ports:
            - "9545:9545"
            - "9546:9546"
            - "30304:30304/tcp"
            - "30304:30304/udp"
        command: >
            --datadir=/base
            --http
            --http.corsdomain="*"
            --http.vhosts="*"
            --http.addr=0.0.0.0
            --http.port=9545
            --http.api=web3,debug,eth,txpool,net,engine
            --ws
            --ws.addr=0.0.0.0
            --ws.port=9546
            --ws.origins="*"
            --ws.api=debug,eth,txpool,net,engine
            --authrpc.addr="0.0.0.0"
            --authrpc.port="9551"
            --authrpc.vhosts="*"
            --authrpc.jwtsecret=/root/jwt/jwt.hex
            --syncmode=snap
            --gcmode=archive
            --maxpeers=100
            --rollup.disabletxpoolgossip=true
            --rollup.sequencerhttp=https://mainnet-sequencer.base.org
            --rollup.halt=major
            --op-network=base-mainnet
            --discovery.port=30304
            --port=30304
    op-node:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
        restart: unless-stopped
        volumes:
            - ./rollup:/root/rollup:ro
            - ./jwttoken:/root/jwt:ro
        ports:
            - "7000:7000" # rpc
            - "9003:9003"
        command: >
            op-node
              --l1=ws://reth:8546
              --l1.trustrpc
              --l2=ws://base-geth:9551
              --l2.jwt-secret=/root/jwt/jwt.hex
              --rollup.config=/root/rollup/rollup.json
              --rpc.addr=0.0.0.0
              --rpc.port=7000
              --network=base-mainnet
              --l1.beacon=http://lighthouse:5052
              --syncmode=execution-layer
        depends_on:
            - reth
            - base-geth
            - lighthouse

volumes:
    base:
        driver: local
