version: "3.9"
name: "reth"

services:
    op-reth:
        restart: unless-stopped
        image: rickybarnett/op-reth
        ports:
            - "9002:9002" # metrics
            - "30304:30304" # eth/66 peering
            - "7545:7545" # rpc
            - "7546:7546" # ws
            - "9551:9551" # engine
        volumes:
            - ~/rethdata_base:/root/.local/share/reth/base/db
            - ~/rethlogs:/root/rethlogs
            - ./jwttoken:/root/jwt:ro
        # For Sepolia, replace `--chain mainnet` with `--chain sepolia`
        command: >
            node
            --chain base
            --rollup.sequencer-http https://mainnet-sequencer.base.org
            --authrpc.addr 0.0.0.0
            --authrpc.port 9551
            --authrpc.jwtsecret /root/jwt/jwt.hex
            --http --http.addr 0.0.0.0 --http.port 7545
            --http.corsdomain "*"
            --http.api "eth,net,web3,txpool,admin,eth-call-bundle,debug,trace"
            --ws --ws.addr 0.0.0.0 --ws.port 7546
            --ws.origins "*"
            --ws.api "eth,net,web3,txpool,admin,eth-call-bundle,debug,trace"
            --rpc-max-response-size 9999999
        depends_on:
            - reth

    op-node:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
        restart: unless-stopped
        volumes:
            - ./rollup:/root/rollup:ro
            - ./jwttoken:/root/jwt:ro
        ports:
            - "7000:7000" # rpc
            - "9003:9003"
        command: >
            op-node
              --l1=ws://reth:8546
              --l1.trustrpc
              --l2=ws://op-reth:9551
              --l2.jwt-secret=/root/jwt/jwt.hex
              --rollup.config=/root/rollup/rollup.json
              --rpc.addr=0.0.0.0
              --rpc.port=7000
              --network=base-mainnet
        depends_on:
            - reth
            - op-reth

volumes:
    rethdata_base:
        driver: local
