version: "3.9"
name: "reth"

services:
    blast-geth:
        image: blastio/blast-geth:testnet-sepolia
        volumes:
            - ~/blast:/blast
            - ./jwttoken:/root/jwt:ro
        ports:
            - "9545:9545"
            - "9546:9546"
        command: >
            --datadir=/blast/blast-geth-data
            --http
            --http.corsdomain="*"
            --http.vhosts="*"
            --http.addr=0.0.0.0
            --http.port=9545
            --http.api=web3,debug,eth,txpool,net,engine
            --ws
            --ws.addr=0.0.0.0
            --ws.port=9546
            --ws.origins="*"
            --ws.api=debug,eth,txpool,net,engine
            --authrpc.addr="0.0.0.0"
            --authrpc.port="9551"
            --authrpc.vhosts="*"
            --authrpc.jwtsecret=/root/jwt/jwt.hex
            --syncmode=full
            --gcmode=archive
            --nodiscover
            --maxpeers=0
            --rollup.disabletxpoolgossip=true
            --rollup.sequencerhttp=https://sequencer.s2.testblast.io
    op-node:
        image: blastio/blast-optimism:testnet-sepolia
        restart: unless-stopped
        volumes:
            - ./rollup:/root/rollup:ro
            - ./jwttoken:/root/jwt:ro
        ports:
            - "7000:7000" # rpc
            - "9003:9003"
        command: >
            op-node
              --l1=ws://reth:8546
              --l1.trustrpc
              --l2=ws://blast-geth:9551
              --l2.jwt-secret=/root/jwt/jwt.hex
              --rollup.config=/root/rollup/rollup.json
              --rpc.addr=0.0.0.0
              --rpc.port=7000
              --p2p.bootnodes=enr:-J-4QM3GLUFfKMSJQuP1UvuKQe8DyovE7Eaiit0l6By4zjTodkR4V8NWXJxNmlg8t8rP-Q-wp3jVmeAOml8cjMj__ROGAYznzb_HgmlkgnY0gmlwhA-cZ_eHb3BzdGFja4X947FQAIlzZWNwMjU2azGhAiuDqvB-AsVSRmnnWr6OHfjgY8YfNclFy9p02flKzXnOg3RjcIJ2YYN1ZHCCdmE,enr:-J-4QDCVpByqQ8nFqCS9aHicqwUfXgzFDslvpEyYz19lvkHLIdtcIGp2d4q5dxHdjRNTO6HXCsnIKxUeuZSPcEbyVQCGAYznzz0RgmlkgnY0gmlwhANiQfuHb3BzdGFja4X947FQAIlzZWNwMjU2azGhAy3AtF2Jh_aPdOohg506Hjmtx-fQ1AKmu71C7PfkWAw9g3RjcIJ2YYN1ZHCCdmE
        depends_on:
            - reth
            - blast-geth

volumes:
    blast:
        driver: local
