version: "3.9"
name: "reth"

services:
    unichain-geth:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101500.0-rc.3
        volumes:
            - ~/unichain:/unichain
            - ./jwttoken:/root/jwt:ro
        ports:
            - "7545:7545"
            - "7546:7546"
            - "30304:30304/tcp"
            - "30304:30304/udp"
        command: >
            --datadir=/unichain
            --http
            --http.corsdomain="*"
            --http.vhosts="*"
            --http.addr=0.0.0.0
            --http.port=7545
            --http.api=web3,debug,eth,txpool,net,engine
            --ws
            --ws.addr=0.0.0.0
            --ws.port=7546
            --ws.origins="*"
            --ws.api=debug,eth,txpool,net,engine
            --authrpc.addr="0.0.0.0"
            --authrpc.port="7551"
            --authrpc.vhosts="*"
            --authrpc.jwtsecret=/root/jwt/jwt.hex
            --syncmode=snap
            --gcmode=full
            --maxpeers=100
            --rollup.disabletxpoolgossip=true
            --rollup.sequencerhttp=https://mainnet-sequencer.unichain.org
            --op-network=unichain-mainnet
            --discovery.port=30304
            --port=30304
            --bootnodes=enode://b1a743328188dba3b2ed8c06abbb2688fabe64a3251e43bd77d4e5265bbd5cf03eca8ace4cde8ddb0c49c409b90bf941ebf556094638c6203edd6baa5ef0091b@3.134.214.169:30303,enode://ea9eaaf695facbe53090beb7a5b0411a81459bbf6e6caac151e587ee77120a1b07f3b9f3a9550f797d73d69840a643b775fd1e40344dea11e7660b6a483fe80e@52.14.30.39:30303,enode://77b6b1e72984d5d50e00ae934ffea982902226fe92fa50da42334c2750d8e405b55a5baabeb988c88125368142a64eda5096d0d4522d3b6eef75d166c7d303a9@3.148.100.173:30303
        stop_grace_period: 5m
    unichain-op-node:
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.11.0-rc.2
        restart: unless-stopped
        volumes:
            - ./jwttoken:/root/jwt:ro
        ports:
            - "7000:7000" # rpc
            - "7003:7003"
        command: >
            op-node
              --l1=ws://reth:8546
              --l1.trustrpc
              --l2=ws://unichain-geth:7551
              --l2.jwt-secret=/root/jwt/jwt.hex
              --rpc.addr=0.0.0.0
              --rpc.port=7000
              --network=unichain-mainnet
              --l1.beacon=http://lighthouse:5052
              --syncmode=execution-layer
        depends_on:
            - reth
            - unichain-geth
            - lighthouse

volumes:
    unichain:
        driver: local
