[package]
name = "reth-node-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-rpc-types.workspace = true
thiserror.workspace = true

# io
serde.workspace = true

[dev-dependencies]
# for examples
reth-payload-builder.workspace = true

[features]
optimism = []
