[package]
name = "reth-node-optimism"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-payload-builder.workspace = true
reth-basic-payload-builder.workspace = true
reth-optimism-payload-builder.workspace = true
reth-rpc-types.workspace = true
reth-rpc.workspace = true
reth-rpc-types-compat.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-tracing.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-network.workspace = true
reth-revm.workspace = true
revm.workspace = true

# misc
clap.workspace = true
serde.workspace = true
eyre.workspace = true
parking_lot.workspace = true

[dev-dependencies]
reth-db.workspace = true

[features]
optimism = [
    "reth-network/optimism",
    "reth-primitives/optimism",
    "reth-transaction-pool/optimism",
    "reth-rpc-types/optimism",
    "reth-provider/optimism",
    "reth-rpc-types-compat/optimism",
    "reth-rpc/optimism",
    "reth-optimism-payload-builder/optimism",
    "reth-revm/optimism",
]
