[package]
name = "reth-net-nat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Helpers for working around NAT"

[lints]
workspace = true

[dependencies]
# nat
public-ip = "0.2"
igd-next = { workspace = true, features = ["aio_tokio"] }

# misc
tracing.workspace = true
pin-project-lite = "0.2.9"
tokio = { workspace = true, features = ["time"] }
thiserror.workspace = true
serde_with = { version = "3.3.0", optional = true }

[dev-dependencies]
reth-tracing.workspace = true
tokio = { workspace = true, features = ["macros"] }

[features]
default = ["serde"]
serde = ["dep:serde_with"]
